name: Build and deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - run: npm ci
      - run: npm run build --base=/glassgen

  deploy:
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Deploy to webserver"
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -av --delete
          path: dist/
          remote_path: /srv/website/2025/glassgen
          remote_host: srv2.mrmcd.net
          remote_user: website
          remote_key: ${{ secrets.SSH_KEY }}
